# Generated by Django 4.0 on 2023-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='service',
            field=models.CharField(choices=[('Excavation', 'Excavation'), ('Re-Sodding', 'Re-Sodding'), ('Interlock', 'Interlock'), ('Concrete', 'Concrete'), ('Asphalt Paving', 'Asphalt Paving'), ('Asphalt Repairs', 'Asphalt Repairs')], default='Excavation', max_length=15),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
