# Generated by Django 4.1 on 2025-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, max_length=340, null=True),
        ),
    ]
