# Generated by Django 4.0 on 2022-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(null=True, upload_to='image/gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='meta_keywords',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='meta_title',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
