# Generated by Django 4.0 on 2023-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_description_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
