# Generated by Django 4.1 on 2026-03-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='image/gallery/thumbnails/'),
        ),
    ]
